version: "3.7"

volumes:
  n8n_data:
    external: true
  qdrant_storage:
    external: true
  caddy_data:
    external: true

networks:
  app-network:
    name: app-network
    driver: bridge

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - QDRANT_HOST=https://qdrant.tungnguyenai.com
      - QDRANT_PORT=6333
      - NODE_EXTRA_CA_CERTS=/files/qdrant_cert.pem
      - N8N_DIAGNOSTICS_ENABLED=true
      - N8N_DIAGNOSTICS_TRUST_PROXY=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files
      - ${DATA_FOLDER}/qdrant_cert.pem:/files/qdrant_cert.pem
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    environment:
      - QDRANT_ALLOW_GRPC=true
      - QDRANT_ALLOW_HTTP=true
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
      - ${DATA_FOLDER}/my_qdrant_config.yml:/qdrant/config/production.yaml
    networks:
      - app-network